spring:
  application:
    name: auth-integration-api

authentication-provider:
  hubspot:
    application:
      id: ${HUBSPOT_APPLICATION_ID}
      client-id: ${HUBSPOT_CLIENT_ID}
      client-secret: ${HUBSPOT_CLIENT_SECRET}
      redirect-uri: ${HUBSPOT_REDIRECT_URI}
      exchange-for-token-url: ${HUBSPOT_EXCHANGE_FOR_TOKEN_URL}